name: Schedule update for other branches
on:
  # Runs every Saturday at noon
  schedule:
    - cron: "0 12 * * SAT"

# Allow running workflows
permissions:
  actions: write

jobs:
  update:
    name: Trigger update on ${{ matrix.branch }}
    runs-on: ubuntu-24.04-arm
    if: github.repository == 'nix-community/nixvim'
    strategy:
      matrix:
        branch:
          - nixos-25.05
          - nixos-24.11
    steps:
      - name: workflow dispatch
        env:
          GH_TOKEN: ${{ github.token }}
          repo: ${{ github.repository }}
          branch: ${{ matrix.branch }}
        run: |
          gh --repo "$repo" workflow run \
            update.yml --ref "$branch"
